### ISSUE TITLE
Make the list more readable

### ISSUE THREAD

**Issue by pwab** [m2n037/awesome-mecheng#11]
As mentioned in #10 the list gets kind of messy.

Compared to [awesome-python](https://github.com/vinta/awesome-python) this seems to be the case because of the overly used sub-categorising. This is especially the case if there are no entries in sub-categories like for example:

---

###### Tutorials/MOOCs/Lectures

---

Also this leads to a massive use of `######`.

It should be considered to:
- Remove sub-categories which have no entries (They could be moved into an issue if you want to remember that you wanted to add something in those categories).
- Change the approach from always using the _Books, Websites, Articles_ and _Tutorials/MOOCs/Lectures_ sections into something less bloated (like adding icons or tags to show what kind of material a link is)
- Divide the whole document into multiple parts

**Comment by m2n037** [comment]
Hi @pwab where can I find some good icons for categorizing into say books, articles, moocs etc.

**Comment by pwab** [comment]
Well there are different approaches for this...

## Emojis

I can totally recommend using unicode emojis. They are working quite well with most services and markdown software (which supports [GFM](https://github.github.com/gfm/)). See [here](https://www.webpagefx.com/tools/emoji-cheat-sheet/) or [here](http://getemoji.com/) for fast access to supported emojis. Or for the complete reference: [unicode.org](http://unicode.org/emoji/charts/full-emoji-list.html).

Some examples:

| Emoji       | Code          |
|:-----------:|:-------------:|
| :books:     | `:books:`     |
| :book:      | `:book:`      |
| :memo:      | `:memo:`      |
| :newspaper: | `:newspaper:` |

## FontAwesome

You can also consider using [FontAwesome](http://fontawesome.io/) (also on [github](https://github.com/FortAwesome/Font-Awesome)). There are cheatsheets as well - like [this one](https://khan.github.io/Font-Awesome/cheatsheet/). But I don't know how to insert them properly. You can use the [png-versions](https://github.com/encharm/Font-Awesome-SVG-PNG) but this leads to a messy insert code (which could be circumvented by including the used icons into the repository into an img-folder and then reference by `![](img/fa-book.png)`:

Some examples with different sizes:

| Icon                                                                                            | Code                                                                                              |
|:-----------------------------------------------------------------------------------------------:|:-------------------------------------------------------------------------------------------------:|
| ![](https://github.com/encharm/Font-Awesome-SVG-PNG/blob/master/black/png/16/book.png?raw=true) | `![](https://github.com/encharm/Font-Awesome-SVG-PNG/blob/master/black/png/16/book.png?raw=true)` |
| ![](https://github.com/encharm/Font-Awesome-SVG-PNG/blob/master/black/png/22/book.png?raw=true) | `![](https://github.com/encharm/Font-Awesome-SVG-PNG/blob/master/black/png/22/book.png?raw=true)` |
| ![](https://github.com/encharm/Font-Awesome-SVG-PNG/blob/master/black/png/24/book.png?raw=true) | `![](https://github.com/encharm/Font-Awesome-SVG-PNG/blob/master/black/png/24/book.png?raw=true)` |
| ![](https://github.com/encharm/Font-Awesome-SVG-PNG/blob/master/black/png/32/book.png?raw=true) | `![](https://github.com/encharm/Font-Awesome-SVG-PNG/blob/master/black/png/32/book.png?raw=true)` |

## Unicode Characters

You can directly input unicode characters too but I'm not sure if the whole set is supported:

| Symbol   | Code          |
|:--------:|:-------------:|
| &#9658;  | `&#9658;`     |
| &#767;   | `&#767;`      |
| &#2400;  | `&#2400;`     |

## My 2 cents

Use **[emojis](#emojis)**! They are well supported on most services (like github, gitlab...), can be interpreted on [github pages](https://help.github.com/articles/emoji-on-github-pages/) and are easily readable in raw markdown formatting `:+1:` :+1: (if not readable enough they still have just a tiny footprint).

**Comment by m2n037** [comment]
You're awesome, @pwab. I will reorganize it as soon as possible.

**Comment by m2n037** [comment]
I have removed all the books/article/website segregation. I have not yet decided on how to show the difference.

**Comment by pwab** [comment]
I like the tagging system used at https://github.com/Kickball/awesome-selfhosted
These `tags` have a small footprint and are searchable strings - which is a big plus compared to emojis.

These `back to top` links are cool too.

**Comment by mike-u** [comment]
Yes, in addition the table of contents gets in the way - it should probably be links.

**Comment by m2n037** [comment]
Yes @mike-u I intend to add it

**Comment by Clockmaker** [comment]
Following what was said by @pwab i'm proposing this legend

 | category | emoji | code |
 | --- | --- | --- |
 | paid content | 💵 | ``:dollar:`` |
 | book | 📕 | ``:closed_book:`` |
 | video | :movie_camera: or :vhs: | `` :movie_camera: or :vhs:`` |
 | online course/book | 📚 | ``:books:`` |
 | notes/slides| 📝 | ``:memo:`` |
 | list | 📑 | ``:bookmarks_tab:`` |
 | journal | 📰 | ``:newspaper:`` |
 | blog | 📅 | ``:date:`` |
 | git-list | :octocat: | ``:octocat:`` |
 | program/webtool | 🔧  | ``:wrench:`` |
 | code/library | 🔩 | ``::nut_and_bolt:`` |
 | cad | 📐 | ``:triangular_ruler:`` |

If we are going to add emoji we should decide a consistent link system;
sometimes we have:
 * [Title by F S Author (year)](#) 

and sometimes

 * [Title, F.S. Author](#) (year)

I personally prefer the last one, but i honestly don't know whats the right way.

**Comment by pwab** [comment]
Fixed by #25.
I will close this issue now. Discussions about tags and categories should be opened with a new issue.
