### ISSUE TITLE
Compress the TOC into one collapsed line

### ISSUE THREAD

**Issue by pwab** [m2n037/awesome-mecheng#29]
## Summary

I want to suggest to compress the table of contents into a one-liner.
I saw this on some github projects and I think this gives a big readme file some advantages:

- A tidier look
- If a string is searched the TOC can be excluded from search by collapsing it
- If the readme is used as a webpage (html conversion, e. g. when using github pages) and the user wants to print the page the TOC can be excluded from the printing output by collapsing it

## This is the current state

 * [Point 1](#point1)
    * [Point 1.1](#point11)
    * [Point 1.2](#point12)
 * [Point 2](#point2)
    * [Point 2.1](#point21)
    * [Point 2.2](#point22)

##  This is the suggestion
<details>
 <summary>Table of Contents</summary>

 * [Point 1](#point1)
    * [Point 1.1](#point11)
    * [Point 1.2](#point12)
 * [Point 2](#point2)
    * [Point 2.1](#point21)
    * [Point 2.2](#point22)
</details>

## This is the code
```markdown
<details>
 <summary>Table of Contents</summary>

 * [Point 1](#point1)
    * [Point 1.1](#point11)
    * [Point 1.2](#point12)
 * [Point 2](#point2)
    * [Point 2.1](#point21)
    * [Point 2.2](#point22)
</details>
```

**Comment by Clockmaker** [comment]
That's a neat idea, I tried this on my [test-branch](https://github.com/Clockmaker/awesome-mecheng/tree/test#table-of-contents)
````html
Table of Contents
-----------------
<details open><summary>Hide/Show</summary><br/>
...
</details>
````
I used the option ``open`` because to me it's more intuitive and skim-friendly;
also you don't lose the contents' anchor.

On a side note, I didn't use sub-lists on purpose (preeetty ugly 😄).
