### ISSUE TITLE
License should be Public Domain

### ISSUE THREAD

**Issue by ghost** [m2n037/awesome-mecheng#33]
As this documentation project mostly consist from *URL-links* to 3rd party resources you couldn't cover them by terms of GNU GPL.

Better switch project to `The Unlicense` or `Creative Commons Zero v1.0 Universal` (last preferred)

- https://help.github.com/articles/licensing-a-repository/#disclaimer
  - http://unlicense.org/
  - https://creativecommons.org/publicdomain/zero/1.0/
- https://github.com/sindresorhus/awesome

**Comment by Clockmaker** [comment]
I'm bumping this, because CC0 is the right choice, period.
GPL is ill-suited for a list of links and it's a real headache if employed (copyright, authors, takedown...)

Forks are growing, but at this stage its still fixable

**Comment by pwab** [comment]
Thanks for bringing this point up.
Vote for [![License: CC0-1.0](https://licensebuttons.net/l/zero/1.0/80x15.png)](http://creativecommons.org/publicdomain/zero/1.0/)

**Comment by m2n037** [comment]
I am closing this as according to my understanding CC is the right choice for now.
