### ISSUE TITLE
Add links to CAD/Engineering Challenges

### ISSUE THREAD

**Issue by ghost** [m2n037/awesome-mecheng#35]
There are many CAD/Engineering Challenges around the world:
- *"Reddit CAD Challenge"* submitted on /r/cad
  - http://reddit.com/r/cad/search?q=cad+challenge
  - *Reddit CAD Challenge (Archive)* - http://github.com/symbian9/reddit_cad_challenge
- *"Fusion 360 Monthly Challenge"* by Autodesk Community Philippines
  - https://knowledge.autodesk.com/support/fusion-360/getting-started/caas/simplecontent/content/join-the-autodesk-fusion-360-monthly-challenge.html
  - Playlists on YouTube - https://www.youtube.com/user/autodeskcomphil/playlists
- *"GrabCAD Challenge"* and other challenges on GrabCAD
  - http://grabcad.com/challenges

P.S.: More coming soon ;-)

**Comment by Clockmaker** [comment]
Start a new section somewhere under [#competition](https://github.com/m2n037/awesome-mecheng#competition)<sup>1</sup> and open a pull request.
Otherwise just wait @m2n037 :wink:

<br><br>
---
<sup>1</sup> btw, why the missing "s" in the anchor
