### ISSUE TITLE
Project suggestion for Projects board

### ISSUE THREAD

**Issue by Aeronautical-Eng** [m2n037/awesome-mecheng#38]
Here is a suggestion to add this "Civilization Starter Kit Mechanical Design Project" to the Projects board

This is a global open source project where mechanical and design engineers can work together to help contribute to designing modular and cost effective easy to build machines. Which will help uplift our global community.  See links below

This website has not been that active lately, but this has a lot to do with its global support, which varies depending on the current interest in this type of open source activity.

This project is also a good example for how future open source mechanical engineering projects could be run.  

https://www.opensourceecology.org/

http://opensourceecology.org/wiki/Main_Page

http://opensourceecology.org/wiki/Global_Village_Construction_Set

**Comment by m2n037** [comment]
You can add a section for the same.
