### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by pwab** [m2n037/awesome-mecheng#4]
Most awesome lists have a CC-BY-4.0 or CC-0 license. Do you mind to add one too?

See [GitHub licensing docs](https://help.github.com/articles/licensing-a-repository/):
> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The Open Source Guide provides additional guidance on choosing the correct license for your project.

**Comment by m2n037** [comment]
I have added the GNU license.
