### ISSUE TITLE
OMG this repo is what I've been dreaming of *.*

### ISSUE THREAD

**Issue by maxiride** [m2n037/awesome-mecheng#43]
Same story here, I always felt envious of how computer sciences had access to endless resources, courses, examples and anything that really helps to understand the topic and study further.

Finally something equivalent for Engineers, love it and just wanted to leave here my compliments for this repo as it is helping me a lot with my Mechatronic Engineering course :D

**Comment by m2n037** [comment]
Thanks for the compliments. Please contribute to the same when you come across an awesome resource. You can always email me.
