### ISSUE TITLE
Is the embedding of the header image legally safe?

### ISSUE THREAD

**Issue by pwab** [m2n037/awesome-mecheng#5]
The link to the source of the embedded header image ( http://cdn.wonderfulengineering.com/wp-content/uploads/2014/06/gear-wallpaper-6.jpg/ ) leads to nowhere.
So I couldn't find a copy left notice or something like that.

**Comment by m2n037** [comment]
Yes, this image is not available now. I will replace it with a new header image from an open source website. Thanks @pwab

**Comment by m2n037** [comment]
Replaced the image
