### ISSUE TITLE
Some suggestions to streamline the list

### ISSUE THREAD

**Issue by pwab** [m2n037/awesome-mecheng#6]
While going through the list I noticed some points that could be improved:

- [x] Move the **Contact Details** and the **Rules and Regulations** into a separate _CONTRIBUTIONS.md_ file
- [x] Convert the entries of the **Table of Contents** to real clickable links
- [x] Move the **To-Do List** to an issue
- [x] Add new _header image_ to the top and also crop it to a more banner-like format
- [x] ~~Provide an .editorconfig file for consistent style (see: http://editorconfig.org/)~~

**Comment by m2n037** [comment]
Great suggestions, feel free to add more. I will keep it as an open issue and comment whenever I solve some of them

**Comment by pwab** [comment]
Fixed by #24, #25 and others.
